In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\shaha\Downloads\Corona_NLP_test.csv")

In [3]:
df

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,TRENDING: New Yorkers encounter empty supermar...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,When I couldn't find hand sanitizer at Fred Me...,Positive
2,3,44955,NaN,02-03-2020,Find out how you can protect yourself and love...,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,#Panic buying hits #NewYork City as anxious sh...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,#toiletpaper #dunnypaper #coronavirus #coronav...,Neutral
...,...,...,...,...,...,...
3793,3794,48746,Israel ??,16-03-2020,Meanwhile In A Supermarket in Israel -- People...,Positive
3794,3795,48747,"Farmington, NM",16-03-2020,Did you panic buy a lot of non-perishable item...,Negative
3795,3796,48748,"Haverford, PA",16-03-2020,Asst Prof of Economics @cconces was on @NBCPhi...,Neutral
3796,3797,48749,NaN,16-03-2020,Gov need to do somethings instead of biar je r...,Extremely Negative
3797,3798,48750,"Arlington, Virginia",16-03-2020,I and @ForestandPaper members are committed to...,Extremely Positive

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3798 entries, 0 to 3797
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   UserName       3798 non-null   int64
 1   ScreenName     3798 non-null   int64
 2   Location       2964 non-null   object
 3   TweetAt        3798 non-null   object
 4   OriginalTweet  3798 non-null   object
 5   Sentiment      3798 non-null   object
dtypes: int64(2), object(4)
memory usage: 178.2+ KB

In [5]:
df.isnull().sum()

UserName           0
ScreenName         0
Location         834
TweetAt            0
OriginalTweet      0
Sentiment          0
dtype: int64

In [6]:
df.shape

(3798, 6)

In [7]:
df["Location"] = df["Location"].fillna("unknown")

In [11]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer

In [12]:
import nltk
import string
punctuation=string.punctuation
nltk.download("stopwords")
from nltk.corpus import stopwords
sp=set(stopwords.words("english"))
nltk.download("punkt")
lemmatizer = WordNetLemmatizer()

def clean(text):
    words=word_tokenize(text)
    words=[word for word in words if word not in sp and word not in punctuation]
    words=[lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shaha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shaha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [13]:
import re

In [14]:
def preprocess_text(text): 
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub("\\W"," ",text)
    text=re.sub('https?://\S+|www\.\S+','',text)
    text=re.sub('<.*?>+','',text)
    text=re.sub('[%s]'% re.escape(string.punctuation),'',text)
    text=re.sub('\n','',text)
    text=re.sub('\w*\d\w*','',text)
    return text

In [15]:
df['OriginalTweet']=df['OriginalTweet'].apply(preprocess_text)
df['OriginalTweet']=df['OriginalTweet'].apply(clean)

In [16]:
df

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,trending new yorkers encounter empty supermark...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,find hand sanitizer fred meyer turned amazon p...,Positive
2,3,44955,unknown,02-03-2020,find protect loved one coronavirus,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,panic buying hit newyork city anxious shopper ...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,toiletpaper dunnypaper coronavirus coronavirus...,Neutral
...,...,...,...,...,...,...
3793,3794,48746,Israel ??,16-03-2020,meanwhile supermarket israel people dance sing...,Positive
3794,3795,48747,"Farmington, NM",16-03-2020,panic buy lot non perishable item echo need fo...,Negative
3795,3796,48748,"Haverford, PA",16-03-2020,asst prof economics cconces nbcphiladelphia ta...,Neutral
3796,3797,48749,unknown,16-03-2020,gov need somethings instead biar je rakyat ass...,Extremely Negative
3797,3798,48750,"Arlington, Virginia",16-03-2020,forestandpaper member committed safety employe...,Extremely Positive

In [81]:
df['Sentiment'] = df['Sentiment'].replace({
    'Extremely Negative': -1,
    'Negative': -1,
    'Neutral': 0,
    'Positive': 1,
    'Extremely Positive': 1
})

In [18]:
df.columns

Index(['UserName', 'ScreenName', 'Location', 'TweetAt', 'OriginalTweet',
       'Sentiment'],
      dtype='object')

In [19]:
df['Sentiment'].unique()

array([-1,  1,  0])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()

In [22]:
en_cols=['UserName', 'ScreenName', 'Location', 'TweetAt']

In [23]:
for i in en_cols:
    df[i]=le.fit_transform(df[i])

In [24]:
x=df['OriginalTweet']

In [25]:
x

0       trending new yorkers encounter empty supermark...
1       find hand sanitizer fred meyer turned amazon p...
2                      find protect loved one coronavirus
3       panic buying hit newyork city anxious shopper ...
4       toiletpaper dunnypaper coronavirus coronavirus...
                              ...
3793    meanwhile supermarket israel people dance sing...
3794    panic buy lot non perishable item echo need fo...
3795    asst prof economics cconces nbcphiladelphia ta...
3796    gov need somethings instead biar je rakyat ass...
3797    forestandpaper member committed safety employe...
Name: OriginalTweet, Length: 3798, dtype: object

In [26]:
y=df['Sentiment']

In [27]:
y

0      -1
1       1
2       1
3      -1
4       0
       ..
3793    1
3794   -1
3795    0
3796   -1
3797    1
Name: Sentiment, Length: 3798, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
x_train.shape

(3038,)

In [31]:
y_train.shape

(3038,)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
vc=CountVectorizer()

In [34]:
xtrain_vc=vc.fit_transform(x_train)
xtest_vc=vc.transform(x_test)

## Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
model_lr=LogisticRegression()

In [37]:
model_lr.fit(xtrain_vc,y_train)

LogisticRegression()

In [38]:
ypred_lr=model_lr.predict(xtest_vc)

In [39]:
ypred_lr

array([ 0, -1,  1,  0, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  0, -1,  1,  0, -1, -1,  1,  1, -1, -1,  0, -1,  1, -1,
       -1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  0, -1,  1,  1, -1,  1, -1,
       -1,  1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1,  1,
        1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  0,  0, -1, -1, -1,  1,
       -1, -1,  0, -1,  1, -1,  0,  0,  1,  1,  1,  1,  1, -1, -1,  0,  1,
        0, -1, -1,  1,  0, -1,  1, -1, -1,  1, -1,  1,  1, -1,  0, -1, -1,
        1,  0,  1,  1,  1, -1, -1,  1, -1, -1, -1,  0,  0,  1, -1, -1, -1,
       -1,  1, -1, -1,  1,  1,  0, -1, -1, -1,  1,  1,  1, -1, -1,  1,  1,
        1,  0, -1,  1, -1, -1,  1, -1, -1,  1,  0, -1, -1,  1, -1, -1,  0,
       -1, -1, -1, -1,  1, -1,  1, -1, -1,  1,  1,  0, -1,  0, -1, -1, -1,
        0,  1,  1,  1, -1,  1, -1, -1,  1,  0, -1, -1,  1,  1, -1,  0,  1,
       -1,  1,  1, -1,  1, -1,  1, -1,  0,  1, -1, -1,  1,  1, -1,  0, -1,
       -1, -1, -1,  0, -1, -1, -1, -1,  1,  1, -1, -1, -1,  0, -1, -1, -1,
        1, -1,  1,  0, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1,
        1, -1,  0,  1, -1,  1,  1,  0, -1, -1,  1, -1, -1,  1,  1,  1,  1,
        1,  1, -1, -1, -1,  1, -1, -1,  1, -1,  0,  0, -1,  0,  1, -1, -1,
        1,  1, -1,  1,  1,  0,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1,
        1, -1,  0,  1,  0, -1, -1, -1,  0, -1,  0,  0,  1,  0,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  0, -1,  1,  0,  0, -1,  1, -1,
       -1, -1, -1, -1, -1,  0,  1, -1,  1,  1,  1,  0, -1, -1,  1, -1, -1,
       -1,  1, -1, -1, -1, -1,  1,  1,  0, -1, -1,  1, -1,  1,  1, -1, -1,
        1, -1, -1, -1,  1,  1,  1,  0,  1, -1,  1,  1,  1,  1, -1, -1, -1,
       -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1,
        1, -1, -1,  1,  1,  1,  0, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1,
       -1, -1,  1, -1, -1,  0, -1,  1, -1,  1,  0,  1, -1,  1, -1,  1,  1,
       -1,  0, -1, -1, -1,  1, -1,  1,  1,  0, -1,  1, -1,  1, -1,  1,  1,
        1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  0,  1, -1,  1,  1,  0,
        1, -1,  1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,
        0, -1,  1,  0, -1, -1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1,  1,  1, -1,  0,  0, -1, -1, -1,  1, -1,  1,  0,
       -1,  1,  1,  0,  1, -1,  1,  1, -1, -1,  1, -1,  1,  0,  0,  1, -1,
       -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  0,  1,
        0, -1,  0,  0,  0, -1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1,
        1,  0, -1,  1,  1,  0,  1,  1,  0,  1,  1, -1, -1,  1, -1, -1, -1,
        1,  1,  1, -1, -1, -1,  1, -1,  1, -1, -1,  1,  1, -1, -1, -1,  1,
        1,  0,  0,  0,  1,  1,  1,  1, -1,  0,  1, -1, -1, -1,  1,  1,  1,
        1,  1, -1, -1,  1,  0, -1,  0, -1, -1, -1, -1, -1,  1, -1, -1,  0,
        1, -1,  1, -1,  1,  1,  0, -1,  1, -1, -1, -1, -1,  1,  0,  1, -1,
        1,  1,  1,  1,  0, -1, -1, -1,  1, -1,  0,  0,  1,  0,  1, -1,  1,
       -1,  1,  1,  0, -1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1,
        0, -1,  0,  1,  1,  1, -1,  0, -1, -1,  1,  0, -1,  1,  1, -1,  1,
        1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  0,  0,  1, -1,  1, -1, -1,
        1,  1,  1,  0,  1, -1, -1,  1, -1,  1,  0,  1,  0, -1,  1,  1,  1,
        0, -1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  0])

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
acc_lr=accuracy_score(y_test,ypred_lr)

In [42]:
acc_lr

0.6644736842105263

## Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
model_rf=RandomForestClassifier()

In [45]:
model_rf.fit(xtrain_vc,y_train)

RandomForestClassifier()

In [46]:
ypred_rf=model_rf.predict(xtest_vc)

In [47]:
acc_rf=accuracy_score(y_test,ypred_rf)

In [48]:
acc_rf

0.6434210526315789

## Decision Tree

In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
model_dt=DecisionTreeClassifier(
     criterion='gini',
    random_state=42)

In [51]:
model_dt.fit(xtrain_vc,y_train)

DecisionTreeClassifier(random_state=42)

In [52]:
ypred_dt=model_dt.predict(xtest_vc)

In [53]:
ypred_dt

array([ 0, -1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,
       -1, -1, -1,  1, -1,  1,  0,  1,  0,  1,  0,  1,  1,  0,  1,  1, -1,
       -1,  1,  0,  0,  1, -1, -1,  1,  1, -1,  1,  0,  1,  1,  1,  0,  1,
       -1,  1, -1,  1, -1, -1, -1,  1,  0,  1,  0,  1, -1, -1, -1, -1,  1,
        1, -1,  1,  0,  1,  1,  1, -1,  1, -1,  1,  1,  0, -1,  1,  1,  0,
        1, -1,  0,  1,  1, -1,  1,  0, -1, -1,  1,  1, -1, -1,  1,  0,  1,
        0, -1, -1, -1,  0, -1, -1, -1, -1,  1, -1,  1,  1, -1,  0, -1, -1,
        1,  0,  0,  1, -1, -1, -1,  1, -1,  0,  1,  0,  0,  1,  0, -1, -1,
       -1,  1, -1,  0,  1,  1,  0, -1, -1, -1,  0,  1,  1,  1, -1, -1, -1,
        1,  1,  0, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  0,
       -1,  1, -1, -1, -1, -1,  1,  0,  0,  1,  1, -1,  0,  1,  1, -1,  0,
        0,  1,  1,  1, -1,  1,  0, -1,  1,  0, -1, -1, -1,  1, -1,  1, -1,
       -1, -1,  1,  1,  1,  1,  0,  0,  0,  0,  1, -1,  1,  1, -1, -1, -1,
       -1, -1,  0,  0, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,
        1, -1,  1,  0,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1,  1,  1,  1,  0,  0, -1,  0,  1, -1, -1, -1, -1,  1, -1,  1,  1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1,
        1,  1, -1,  1,  0,  0, -1, -1, -1, -1,  1,  1, -1,  0,  0,  1, -1,
       -1, -1, -1, -1, -1, -1,  1,  0,  0,  0,  1,  1,  1,  0,  1,  0,  0,
        1,  1,  1,  1,  1,  1,  0,  1,  1,  0, -1,  0,  0,  0, -1,  0, -1,
        1, -1, -1, -1, -1,  0,  0, -1,  1, -1,  1,  0, -1, -1,  1, -1, -1,
       -1,  0, -1,  0,  0, -1,  1, -1,  1, -1, -1,  0, -1,  1, -1, -1,  1,
       -1,  1,  0,  1, -1,  1,  1, -1,  0, -1,  1,  1,  1, -1,  1, -1, -1,
        1, -1, -1, -1, -1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  0,  1, -1,
       -1,  1,  1, -1,  1,  1,  0,  0,  1,  1,  1,  1, -1, -1, -1,  1,  1,
       -1, -1,  1, -1, -1,  0, -1, -1, -1,  1,  0, -1,  0, -1,  0,  1,  1,
       -1,  1,  0,  1, -1,  1, -1,  1,  1,  0,  1, -1, -1,  1, -1,  1,  1,
        1,  1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  0,  1, -1, -1,  1,  1,
        1,  0, -1, -1,  1,  1,  1,  0, -1,  0,  1, -1,  1,  1,  1, -1,  1,
       -1, -1,  0,  0, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1,
       -1, -1,  1,  1,  0, -1,  1, -1,  0, -1, -1, -1, -1,  1,  1, -1,  1,
       -1,  1,  0,  0,  1, -1,  1, -1, -1,  0, -1, -1, -1,  0,  1, -1, -1,
       -1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  0, -1, -1, -1,  1,
        1, -1,  0,  1,  1,  0, -1,  1,  1,  0, -1, -1,  0,  0, -1, -1,  1,
        1,  0,  1,  1,  1, -1,  1, -1, -1,  1,  0,  1,  0,  1, -1, -1, -1,
        1,  1,  1,  0, -1, -1,  1,  0, -1, -1, -1,  1,  0, -1,  1,  1,  0,
        1,  0,  0, -1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,
        1,  1,  1, -1,  1,  0,  0,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,
       -1, -1, -1,  1,  1,  0,  0, -1,  1,  1, -1, -1,  0,  1, -1,  0, -1,
        1,  1,  0, -1,  1, -1, -1, -1,  1, -1,  0,  0, -1,  0,  1,  1,  1,
       -1,  1, -1,  0,  1,  0, -1,  1,  0,  1,  1, -1, -1,  1,  1, -1,  1,
        1,  0, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1,  1,  1,
        1,  0, -1, -1, -1,  0, -1,  1,  0, -1,  0, -1,  1, -1, -1, -1,  0,
        0,  0,  1,  0,  1, -1, -1,  0, -1,  1,  0,  1,  0, -1,  1, -1,  1,
        0, -1, -1, -1,  1, -1,  1,  1,  1,  0,  1,  0])

In [54]:
acc_dt=accuracy_score(y_test,ypred_dt)

In [55]:
acc_dt

0.5618421052631579

## Support Vector Machine

### SVC (Linear)

In [56]:
from sklearn.svm import SVC

In [57]:
model_svl=SVC(kernel='linear')

In [58]:
model_svl.fit(xtrain_vc,y_train)

SVC(kernel='linear')

In [59]:
ypred_svl=model_svl.predict(xtest_vc)

In [60]:
acc_svl=accuracy_score(y_test,ypred_svl)

In [61]:
acc_svl

0.6644736842105263

### SVC (RBF)

In [62]:
model_svr=SVC(kernel='rbf')

In [63]:
model_svr.fit(xtrain_vc,y_train)

SVC()

In [64]:
ypred_svr=model_svr.predict(xtest_vc)

In [65]:
acc_svr=accuracy_score(y_test,ypred_svr)

In [66]:
acc_svr

0.6460526315789473

In [67]:
from tabulate import tabulate

In [68]:
table=[["MODEL","R2"],['Logistic Regression',acc_lr],['Random Forest',acc_rf],
       ['Decision Tree',acc_dt],['SVR(linear)',acc_svl],['SVR(RBF)',acc_svr]]

In [69]:
print(tabulate(table,headers='firstrow',tablefmt='fancy_grid'))

╒═════════════════════╤══════════╕
│ MODEL               │       R2 │
╞═════════════════════╪══════════╡
│ Logistic Regression │ 0.664474 │
├─────────────────────┼──────────┤
│ Random Forest       │ 0.643421 │
├─────────────────────┼──────────┤
│ Decision Tree       │ 0.561842 │
├─────────────────────┼──────────┤
│ SVR(linear)         │ 0.664474 │
├─────────────────────┼──────────┤
│ SVR(RBF)            │ 0.646053 │
╘═════════════════════╧══════════╛

In [70]:
df['OriginalTweet'].unique()

array(['trending new yorkers encounter empty supermarket shelf pictured wegmans brooklyn sold online grocer foodkick maxdelivery coronavirus fearing shopper stock http co http co',
       'find hand sanitizer fred meyer turned amazon pack purell check coronavirus concern driving price http co ygbipbflmy',
       'find protect loved one coronavirus', ...,
       'asst prof economics cconces nbcphiladelphia talking recent research coronavirus impact economy watch starting http co',
       'gov need somethings instead biar je rakyat assume lockdown ke even worst harini semua supermarket crowded like hell lagi mudah virus tu tersebar',
       'forestandpaper member committed safety employee end user monitoring covid rest assured tissue manufacturer continuing produce ship product http co http co xyvbnsfexa'],
      dtype=object)

In [71]:
new_message=['forestandpaper member committed safety employee end user monitoring covid rest assured tissue manufacturer continuing produce ship product http co http co xyvbnsfexa']

In [72]:
new_message_vc=vc.transform(new_message)

In [74]:
prediction=model_lr.predict(new_message_vc)

In [75]:
print(prediction)

[1]